export interface IBook {
  id: string;
  title: string;
  author: string;
  genre: string;
  publishedYear: number;
  status: string;
  image: string;
}

export const books: IBook[] = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic",
    publishedYear: 1925,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
  },
  {
    id: "2",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Classic",
    publishedYear: 1960,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
  },
  {
    id: "3",
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    publishedYear: 1949,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/7222246-M.jpg",
  },
  {
    id: "4",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Classic",
    publishedYear: 1951,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
  },
  {
    id: "5",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    publishedYear: 1813,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
  },
  {
    id: "6",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    publishedYear: 1937,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/6979861-L.jpg",
  },
  {
    id: "7",
    title: "Harry Potter and the Sorcerer’s Stone",
    author: "J.K. Rowling",
    genre: "Fantasy",
    publishedYear: 1997,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/7984916-L.jpg",
  },
  {
    id: "8",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    genre: "Thriller",
    publishedYear: 2003,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/240726-L.jpg",
  },
  {
    id: "9",
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Adventure",
    publishedYear: 1988,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/8128691-L.jpg",
  },
  {
    id: "10",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    genre: "Drama",
    publishedYear: 2003,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/8225269-L.jpg",
  },
  {
    id: "11",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    genre: "Dystopian",
    publishedYear: 2008,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/7261823-L.jpg",
  },
  {
    id: "12",
    title: "Becoming",
    author: "Michelle Obama",
    genre: "Biography",
    publishedYear: 2018,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/9255320-L.jpg",
  },
  {
    id: "13",
    title: "Educated",
    author: "Tara Westover",
    genre: "Memoir",
    publishedYear: 2018,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/9254716-L.jpg",
  },
  {
    id: "14",
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-Help",
    publishedYear: 2018,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/9254895-L.jpg",
  },
  {
    id: "15",
    title: "The Lean Startup",
    author: "Eric Ries",
    genre: "Business",
    publishedYear: 2011,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/8663314-L.jpg",
  },
  {
    id: "16",
    title: "The Shining",
    author: "Stephen King",
    genre: "Horror",
    publishedYear: 1977,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/8231851-L.jpg",
  },
  {
    id: "17",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    publishedYear: 1954,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/8729516-L.jpg",
  },
  {
    id: "18",
    title: "Moby-Dick",
    author: "Herman Melville",
    genre: "Classic",
    publishedYear: 1851,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/7222161-L.jpg",
  },
  {
    id: "19",
    title: "War and Peace",
    author: "Leo Tolstoy",
    genre: "Historical",
    publishedYear: 1869,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/7222276-L.jpg",
  },
  {
    id: "20",
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    genre: "Philosophical",
    publishedYear: 1866,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/8235080-L.jpg",
  },
  {
    id: "21",
    title: "The Girl with the Dragon Tattoo",
    author: "Stieg Larsson",
    genre: "Thriller",
    publishedYear: 2005,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/8232001-L.jpg",
  },
  {
    id: "22",
    title: "Gone Girl",
    author: "Gillian Flynn",
    genre: "Thriller",
    publishedYear: 2012,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/8231836-L.jpg",
  },
  {
    id: "23",
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian",
    publishedYear: 1932,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/7222248-L.jpg",
  },
  {
    id: "24",
    title: "The Road",
    author: "Cormac McCarthy",
    genre: "Post-Apocalyptic",
    publishedYear: 2006,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/8226190-L.jpg",
  },
  {
    id: "25",
    title: "Life of Pi",
    author: "Yann Martel",
    genre: "Adventure",
    publishedYear: 2001,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/7222175-L.jpg",
  },
  {
    id: "26",
    title: "The Fault in Our Stars",
    author: "John Green",
    genre: "Romance",
    publishedYear: 2012,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/7875051-L.jpg",
  },
  {
    id: "27",
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    genre: "Fantasy",
    publishedYear: 1996,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/7291618-L.jpg",
  },
  {
    id: "28",
    title: "The Book Thief",
    author: "Markus Zusak",
    genre: "Historical",
    publishedYear: 2005,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/8226193-L.jpg",
  },
  {
    id: "29",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    genre: "Non-Fiction",
    publishedYear: 2011,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/9254748-L.jpg",
  },
  {
    id: "30",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    genre: "Thriller",
    publishedYear: 2019,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/9875678-L.jpg",
  },
];
