// books.fixture.ts

export const books = [
  {
    id: "1",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic",
    publishedYear: 1925,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/7222246-L.jpg",
  },
  {
    id: "2",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Classic",
    publishedYear: 1960,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
  },
  {
    id: "3",
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    publishedYear: 1949,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/7222246-M.jpg",
  },
  {
    id: "4",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Classic",
    publishedYear: 1951,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/8231996-L.jpg",
  },
  {
    id: "5",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    publishedYear: 1813,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/8091016-L.jpg",
  },
  {
    id: "6",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    publishedYear: 1937,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/6979861-L.jpg",
  },
  {
    id: "7",
    title: "Harry Potter and the Sorcerer’s Stone",
    author: "J.K. Rowling",
    genre: "Fantasy",
    publishedYear: 1997,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/7984916-L.jpg",
  },
  {
    id: "8",
    title: "The Da Vinci Code",
    author: "Dan Brown",
    genre: "Thriller",
    publishedYear: 2003,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/240726-L.jpg",
  },
  {
    id: "9",
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Adventure",
    publishedYear: 1988,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/8128691-L.jpg",
  },
  {
    id: "10",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    genre: "Drama",
    publishedYear: 2003,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/8225269-L.jpg",
  },
  {
    id: "11",
    title: "The Hunger Games",
    author: "Suzanne Collins",
    genre: "Dystopian",
    publishedYear: 2008,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/7261823-L.jpg",
  },
  {
    id: "12",
    title: "Becoming",
    author: "Michelle Obama",
    genre: "Biography",
    publishedYear: 2018,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/9255320-L.jpg",
  },
  {
    id: "13",
    title: "Educated",
    author: "Tara Westover",
    genre: "Memoir",
    publishedYear: 2018,
    status: "Issued",
    image: "https://covers.openlibrary.org/b/id/9254716-L.jpg",
  },
  {
    id: "14",
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-Help",
    publishedYear: 2018,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/9254895-L.jpg",
  },
  {
    id: "15",
    title: "The Lean Startup",
    author: "Eric Ries",
    genre: "Business",
    publishedYear: 2011,
    status: "Available",
    image: "https://covers.openlibrary.org/b/id/8663314-L.jpg",
  },
];
